name: Linux_Container_Workflow
on: [workflow_dispatch]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push frontend image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.SP_CLIENT_ID }}
            password: ${{ secrets.SP_SECRET }}
        - run: |
            docker build ./frontend -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}

        # - name: 'Deploy to Azure Container Instances'
        #   uses: 'azure/aci-deploy@v1'
        #   with:
        #     resource-group: ${{ secrets.RESOURCE_GROUP }}
        #     dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        #     image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}
        #     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
        #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        #     name: crispy-frontend-instance
        #     location: 'east us'

        - uses: azure/webapps-deploy@v2
          with:
            app-name: 'webapp-msa-crispy-frontend-wings'
            images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}

        - uses: azure/appservice-settings@v1
          with:
            app-name: 'webapp-msa-crispy-frontend-wings'
            app-settings-json: '${{ secrets.APPSETTINGS_FRONTEND }}'